services:
  template:
    build: .
    image: template
    container_name: template
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/src
      - ./scripts:/scripts
    command: ["/scripts/start.sh"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=template
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

