# Generated by Django 5.0.7 on 2024-09-08 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRecoverPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('code', models.IntegerField(verbose_name='Codigo de seguridad')),
                ('expiration', models.DateTimeField(verbose_name='tiempo de valido  del codigo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Codigo de seguridad restablecimiento de contraseña',
                'verbose_name_plural': 'Codigos de seguridad restablecimiento de contraseñas',
            },
        ),
    ]
